# for development only
version: "3"
services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: prisma
      POSTGRES_USER: prisma
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
  # pgadmin:
  #   image: dpage/pgadmin4
  #   restart: always
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: dev@dev.com
  #     PGADMIN_DEFAULT_PASSWORD: dev
  #   ports:
  #     - 5050:80
volumes:
  postgres-data:
